//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AH_USERGROUP_PERM
    {
        public string GROUP_ID { get; set; }
        public short DEPT_ID { get; set; }
        public short REPORT_TYPE_ID { get; set; }
        public short PRIORITY { get; set; }
        public short AUTO_ASSIGN_CHK { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual AH_USER_GROUP AH_USER_GROUP { get; set; }
        public virtual DEPARTMENTS DEPARTMENTS { get; set; }
        public virtual REPORTDESC REPORTDESC { get; set; }
    }
}
