//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENTS
    {
        public DEPARTMENTS()
        {
            this.AH_USERGROUP_PERM = new HashSet<AH_USERGROUP_PERM>();
            this.RECS = new HashSet<RECS>();
            this.USERS = new HashSet<USERS>();
        }
    
        public short ID_DEPARTMENT { get; set; }
        public string DEPARTMANT_NAME { get; set; }
        public string DP_CREATE_USER { get; set; }
        public Nullable<System.DateTime> DP_CREATE_DATE { get; set; }
        public string DP_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> DP_UPDATE_DATE { get; set; }
    
        public virtual ICollection<AH_USERGROUP_PERM> AH_USERGROUP_PERM { get; set; }
        public virtual ICollection<RECS> RECS { get; set; }
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
