//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainerEntities : DbContext
    {
        public ModelContainerEntities()
            : base("name=ModelContainerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AH_USER> AH_USER { get; set; }
        public DbSet<AH_USER_GROUP> AH_USER_GROUP { get; set; }
        public DbSet<AH_USERGROUP_PERM> AH_USERGROUP_PERM { get; set; }
        public DbSet<DEPARTMENTS> DEPARTMENTS { get; set; }
        public DbSet<GENERAL_PARAMETER> GENERAL_PARAMETER { get; set; }
        public DbSet<HOSPITALS> HOSPITALS { get; set; }
        public DbSet<MLIST_NEW> MLIST_NEW { get; set; }
        public DbSet<PATIENTS> PATIENTS { get; set; }
        public DbSet<REC_STATE> REC_STATE { get; set; }
        public DbSet<RECS> RECS { get; set; }
        public DbSet<REPORT_COLUMNS> REPORT_COLUMNS { get; set; }
        public DbSet<REPORTDESC> REPORTDESC { get; set; }
        public DbSet<TEMPLATE_SUBSTITUTION> TEMPLATE_SUBSTITUTION { get; set; }
        public DbSet<TRANS> TRANS { get; set; }
        public DbSet<USERS> USERS { get; set; }
    }
}
