//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENTS
    {
        public PATIENTS()
        {
            this.RECS = new HashSet<RECS>();
        }
    
        public string PA_PROT_ID { get; set; }
        public string PA_NAME_NUM { get; set; }
        public string PA_PRIORITY { get; set; }
        public string PA_NAME { get; set; }
        public string PA_NAMEREV { get; set; }
    
        public virtual ICollection<RECS> RECS { get; set; }
    }
}
