//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_STATE
    {
        public REC_STATE()
        {
            this.RECS = new HashSet<RECS>();
        }
    
        public short RC_STATE { get; set; }
        public string STATE_DESC { get; set; }
    
        public virtual ICollection<RECS> RECS { get; set; }
    }
}
