//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE_SUBSTITUTION
    {
        public string TAB_NAME { get; set; }
        public string COL_NAME { get; set; }
        public string REPLACE_STRING { get; set; }
        public Nullable<short> BEFORE_AFTER { get; set; }
        public short ID { get; set; }
        public string DATE_TYPE { get; set; }
    }
}
