//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS
    {
        public string TR_RECID { get; set; }
        public string TR_TRANSCRIBER { get; set; }
        public string TR_DOCNAME { get; set; }
        public Nullable<System.DateTime> TR_STARTDATE { get; set; }
        public Nullable<System.DateTime> TR_STOPDATE { get; set; }
    
        public virtual AH_USER AH_USER { get; set; }
        public virtual RECS RECS { get; set; }
    }
}
