//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.RECS = new HashSet<RECS>();
            this.REPORTDESC = new HashSet<REPORTDESC>();
        }
    
        public string US_CODE { get; set; }
        public string US_PASSWD { get; set; }
        public string US_NAME { get; set; }
        public short US_ACTIVE { get; set; }
        public string US_PHONE { get; set; }
        public short US_DEPID { get; set; }
        public string US_HOSPITAL { get; set; }
        public string US_FLAGS { get; set; }
        public string US_CREATE_USER { get; set; }
        public Nullable<System.DateTime> US_CREATE_DATE { get; set; }
        public string US_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> US_UPDATE_DATE { get; set; }
    
        public virtual DEPARTMENTS DEPARTMENTS { get; set; }
        public virtual ICollection<RECS> RECS { get; set; }
        public virtual ICollection<REPORTDESC> REPORTDESC { get; set; }
    }
}
