//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam Et.
        /// </summary>
        internal static string BtnGoHead {
            get {
                return ResourceManager.GetString("BtnGoHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Bağlantısı.
        /// </summary>
        internal static string BtnTestConnection {
            get {
                return ResourceManager.GetString("BtnTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komut Yazınız.
        /// </summary>
        internal static string CommandText {
            get {
                return ResourceManager.GetString("CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Adı.
        /// </summary>
        internal static string DbName {
            get {
                return ResourceManager.GetString("DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Şifre.
        /// </summary>
        internal static string DbPassword {
            get {
                return ResourceManager.GetString("DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Tabloları.
        /// </summary>
        internal static string DbTables {
            get {
                return ResourceManager.GetString("DbTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Kullanıcı Adı.
        /// </summary>
        internal static string DbUser {
            get {
                return ResourceManager.GetString("DbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox Turkey Giriş.
        /// </summary>
        internal static string LoginViewHeaderText {
            get {
                return ResourceManager.GetString("LoginViewHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Tabanı Adını Yazınız....
        /// </summary>
        internal static string PlaceHolderDbName {
            get {
                return ResourceManager.GetString("PlaceHolderDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre....
        /// </summary>
        internal static string PlaceHolderDbPassword {
            get {
                return ResourceManager.GetString("PlaceHolderDbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı....
        /// </summary>
        internal static string PlaceHolderDbUserName {
            get {
                return ResourceManager.GetString("PlaceHolderDbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi Yazınız....
        /// </summary>
        internal static string PlaceHolderPassword {
            get {
                return ResourceManager.GetString("PlaceHolderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Adını Yazınız....
        /// </summary>
        internal static string PlaceHolderServerName {
            get {
                return ResourceManager.GetString("PlaceHolderServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adınızı Yazınız....
        /// </summary>
        internal static string PlaceHolderUserName {
            get {
                return ResourceManager.GetString("PlaceHolderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komutu Çalıştır.
        /// </summary>
        internal static string RunCommand {
            get {
                return ResourceManager.GetString("RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Adı.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox Turkey.
        /// </summary>
        internal static string WebSiteTitle {
            get {
                return ResourceManager.GetString("WebSiteTitle", resourceCulture);
            }
        }
    }
}
